title: My Site
description: My awesome docs

remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

color_scheme: dark   # or light

search_enabled: true

nav_enabled: true

heading_anchors: true

aux_links:
  "View on GitHub":
    - "https://github.com/UrvishkumarPatel/ai_tools"

back_to_top: true
back_to_top_text: "Back to top"

markdown: kramdown

kramdown:
  input: GFM


# just_the_docs:
#   collections:
#     docs:
#       name: Docs

# collections:
#   docs:
#     output: true